apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
  name: cls02-jmt7t-infra
  generation: 1
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cls02-jmt7t
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cls02-jmt7t
      machine.openshift.io/cluster-api-machineset: cls02-jmt7t-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cls02-jmt7t
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: cls02-jmt7t-infra
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          numCoresPerSocket: 4
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 16384
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: MGMT_OCP
          metadata:
            creationTimestamp: null
          numCPUs: 4
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: IT1
            datastore: DATASTORE01
            folder: /IT1/vm/cls02-jmt7t
            resourcePool: /IT1/host/OCP/Resources
            server: ipit1-rhovcr01.poc.local
          template: cls02-jmt7t-rhcos
          apiVersion: machine.openshift.io/v1beta1
